name = "ygsite"
compatibility_date = "2025-06-08"

main = "workers-site/index.js"

route = { pattern = "yuktigirdhar.com/*", zone_name = "yuktigirdhar.com" }

[assets]
directory = "./dist"
binding = "ASSETS"
